### ISSUE TITLE
项目不更新了吗? 

### ISSUE THREAD

**Issue by dmhai** [MZ-FE/vue-vite-h5#3]
还有请求、路由之类的没有写，

建议写个登录、首页、个人中心页，这样请求、路由、导航、布局之类的都有了。

**Comment by worldsoon** [comment]
![image](https://github.com/MZ-FE/vue-vite-h5/assets/10103820/7235d571-4d02-47c2-92b8-d758fc1436c6)
路由和请求都有了，你是想要个完整页面的demo吧

**Comment by dmhai** [comment]
对，前端新手，刚挑选脚手架，想找个demo一边修改一边学习，我之前是想看看，具体怎么把这几个知识点实际应用到页面上，毕竟封装集成和应用是个纠结的问题，如果有个应用示例页面，我就不用纠结了，直接按照你写的改改就行了。

可能我没表达清楚，我上面的话或许可以改改：
【建议写一下登录、首页、个人中心这3个页面，这样一来，请求、路由、导航、布局之类应用示例都有了】

额，可能是有点贪？不过我觉得这是个快速入门的方式，我后端就是这样学的，找个相对完善的权限管理框架，然后对照框架的方式，依样画葫芦添加页面和调用各种东西，你这个项目技术栈已经很完善了，如果有页面，直接就能做项目，一边改一边学了。

不过我现在搞清楚了很多了，毕竟有点久了，我找了个别的示例，带示例页面和请求的demo，虽然技术栈没有你这个项目完善，但是能用。

所以这个 issue 我就关了。
